### ISSUE TITLE
Consider supporting more networktype: OVNKubernetes

### ISSUE THREAD

**Issue by pichuang** [RedHatOfficial/ocp4-vsphere-upi-automation#74]
Could we consider refactor those codes to support OVNKubernetes?

https://github.com/RedHatOfficial/ocp4-vsphere-upi-automation/blob/master/roles/common/tasks/isolation_mode.yml#L12-L21

OCP 4.6 can support OpenShiftSDN and OVNKubernetes both.

https://docs.openshift.com/container-platform/4.6/installing/installing_vsphere/installing-vsphere-network-customizations.html#network-customization-config-yaml_installing-vsphere-network-customizations

**Comment by mallmen** [comment]
Added an option to `group_vars/all.yml` to specify the networkType.  The install_config.yaml.j2 template will then use that value when specified, otherwise OpenShiftSDN is used.  Only OpenShiftSDN and OVNKubernetes are valid values for install.  Assert statement added to check for valid value on `config.networkType` when defined.
